-- AUTO-GENERATED by scripts/generate-seed.ts from src/data/seedBooks.ts. Do not edit by hand.
-- Regenerate with: bun run db:seed

INSERT INTO public.books
SELECT * FROM jsonb_populate_recordset(NULL::public.books, '[
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "book-quijote",
    "title": "Don Quijote de la Mancha",
    "author": "Miguel de Cervantes",
    "year": 1605,
    "language": "es",
    "cover_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    "backdrop_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=80",
    "synopsis": "Alonso Quijano, enloquecido por la lectura de libros de caballerías, se nombra caballero andante como Don Quijote y sale a los caminos de La Mancha con su fiel escudero Sancho Panza para desfacer agravios y conquistar la gloria en honor a su dama Dulcinea del Toboso.",
    "source_text_url": "https://www.gutenberg.org/ebooks/2000",
    "genres": [
      "Aventura",
      "Sátira",
      "Filosofía",
      "Clásico"
    ],
    "era": "Siglo de Oro",
    "status": "ready",
    "rating": 4.95,
    "total_views": 489200,
    "featured": true,
    "kids_friendly": true
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "book-celestina",
    "title": "La Celestina",
    "author": "Fernando de Rojas",
    "year": 1499,
    "language": "es",
    "cover_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    "backdrop_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80",
    "synopsis": "El joven noble Calisto se enamora perdidamente de Melibea. Rechazado en un primer encuentro, acude a los consejos de su criado Sempronio y contrata los servicios de la vieja alcahueta y hechicera Celestina, desatando una espiral de pasión, avaricia y tragedia.",
    "source_text_url": "https://www.gutenberg.org/ebooks/1619",
    "genres": [
      "Tragedia",
      "Romance",
      "Drama",
      "Picaresca"
    ],
    "era": "Renacimiento",
    "status": "ready",
    "rating": 4.88,
    "total_views": 312450,
    "featured": true,
    "kids_friendly": false
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "book-regenta",
    "title": "La Regenta",
    "author": "Leopoldo Alas «Clarín»",
    "year": 1884,
    "language": "es",
    "cover_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    "backdrop_url": "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1600&q=80",
    "synopsis": "En la opresiva y murmuradora ciudad de Vetusta, la bella y soñadora Ana Ozores, casada con el anciano regente don Víctor Quintanar, se debate atormentada entre la devoción mística hacia su confesor don Fermín de Pas y la seducción mundana del donjuán Álvaro Mesía.",
    "source_text_url": "https://www.gutenberg.org/ebooks/17070",
    "genres": [
      "Drama",
      "Realismo",
      "Psicológico",
      "Pasión"
    ],
    "era": "Realismo",
    "status": "ready",
    "rating": 4.92,
    "total_views": 275800,
    "featured": true,
    "kids_friendly": false
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "book-fortunata",
    "title": "Fortunata y Jacinta",
    "author": "Benito Pérez Galdós",
    "year": 1887,
    "language": "es",
    "cover_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    "backdrop_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1600&q=80",
    "synopsis": "Fresco colosal del Madrid de fines del siglo XIX. Dos mujeres de clases sociales opuestas quedan unidas por el amor apasionado al caprichoso Juanito Santa Cruz: Fortunata, impulsiva mujer del pueblo, y Jacinta, virtuosa esposa burguesa que anhela un hijo.",
    "source_text_url": "https://www.gutenberg.org/ebooks/17415",
    "genres": [
      "Realismo",
      "Drama",
      "Social",
      "Romance"
    ],
    "era": "Realismo",
    "status": "ready",
    "rating": 4.89,
    "total_views": 198300,
    "featured": false,
    "kids_friendly": false
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "book-becquer",
    "title": "Rimas y Leyendas",
    "author": "Gustavo Adolfo Bécquer",
    "year": 1871,
    "language": "es",
    "cover_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    "backdrop_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
    "synopsis": "Obra cumbre del romanticismo tardío español que aúna poemas etéreos sobre el amor inalcanzable con relatos sobrenaturales y leyendas góticas de templarios, apariciones, campanas fantasmales y ojos verdes en lagunas malditas.",
    "source_text_url": "https://www.gutenberg.org/ebooks/2486",
    "genres": [
      "Gótico",
      "Romanticismo",
      "Misterio",
      "Poesía"
    ],
    "era": "Romanticismo",
    "status": "ready",
    "rating": 4.94,
    "total_views": 341900,
    "featured": false,
    "kids_friendly": true
  }
]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.characters
SELECT * FROM jsonb_populate_recordset(NULL::public.characters, '[
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-quijote",
    "book_id": "book-quijote",
    "name": "Don Quijote",
    "description": "Hidalgo manchego de unos cincuenta años, enjuto de rostro y seco de carnes. Su obsesión idealista lo lleva a desafiar al mundo por justicia.",
    "role": "protagonista",
    "personality": "Idealista, apasionado, noble y delirante",
    "gender": "masculino",
    "age_range": "50-55 años",
    "voice_id": "voice-cervantes-1",
    "voice_name": "Fenrir (Voz grave y solemne)",
    "avatar_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-sancho",
    "book_id": "book-quijote",
    "name": "Sancho Panza",
    "description": "Labrador vecino de Don Quijote, práctico, pragmático y de buen comer, leal compañero de aventuras.",
    "role": "secundario",
    "personality": "Pragmático, socarrón, refranero y entrañable",
    "gender": "masculino",
    "age_range": "40-45 años",
    "voice_id": "voice-sancho-1",
    "voice_name": "Puck (Voz rústica y cálida)",
    "avatar_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-dulcinea",
    "book_id": "book-quijote",
    "name": "Dulcinea del Toboso",
    "description": "Aldeana llamada Aldonza Lorenzo, transfigurada por la mente de Don Quijote en princesa de suprema hermosura.",
    "role": "secundario",
    "personality": "Mítica, distante, terrenal en secreto",
    "gender": "femenino",
    "age_range": "20-25 años",
    "voice_id": "voice-dulcinea-1",
    "voice_name": "Kore (Voz lírica y dulce)",
    "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-celestina",
    "book_id": "book-celestina",
    "name": "Celestina",
    "description": "Vieja alcahueta, astuta y experta en las debilidades humanas, conocedora de filtros de amor y pactos oscuros.",
    "role": "antagonista",
    "personality": "Manipuladora, codiciosa, elocuente y cínica",
    "gender": "femenino",
    "age_range": "60+ años",
    "voice_id": "voice-celestina-1",
    "voice_name": "Charon (Voz rasposa y teatral)",
    "avatar_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-calisto",
    "book_id": "book-celestina",
    "name": "Calisto",
    "description": "Joven de linaje noble, consumido por un deseo ciego e impaciente que raya en la insensatez.",
    "role": "protagonista",
    "personality": "Arrebatado, melodramático e impaciente",
    "gender": "masculino",
    "age_range": "22-26 años",
    "voice_id": "voice-calisto-1",
    "voice_name": "Zephyr (Voz juvenil apasionada)",
    "avatar_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-melibea",
    "book_id": "book-celestina",
    "name": "Melibea",
    "description": "Doncella de rica familia, firme en sus principios hasta que el sortilegio y la palabra de Celestina ablandan su corazón.",
    "role": "protagonista",
    "personality": "Orgullosa, apasionada y trágica",
    "gender": "femenino",
    "age_range": "19-22 años",
    "voice_id": "voice-melibea-1",
    "voice_name": "Kore (Voz melódica con desgarro)",
    "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-ana",
    "book_id": "book-regenta",
    "name": "Ana Ozores",
    "description": "La Regenta, mujer de belleza deslumbrante y espíritu exaltado, presa de la soledad y la hipocresía social.",
    "role": "protagonista",
    "personality": "Romántica, melancólica, vulnerable y profunda",
    "gender": "femenino",
    "age_range": "27-30 años",
    "voice_id": "voice-ana-1",
    "voice_name": "Kore (Voz íntima y contenida)",
    "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-fermin",
    "book_id": "book-regenta",
    "name": "Don Fermín de Pas",
    "description": "El Magistral de la catedral de Vetusta, orador sagrado brillante y ambicioso, cuya pasión oculta por Ana lo destruirá.",
    "role": "antagonista",
    "personality": "Poderoso, celoso, dominante y conflictivo",
    "gender": "masculino",
    "age_range": "35-38 años",
    "voice_id": "voice-fermin-1",
    "voice_name": "Fenrir (Voz resonante eclesiástica)",
    "avatar_url": "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-alvaro",
    "book_id": "book-regenta",
    "name": "Álvaro Mesía",
    "description": "Jefe del partido liberal en Vetusta y reputado conquistador de damas de sociedad.",
    "role": "secundario",
    "personality": "Frívolo, elegante, seductor y calculador",
    "gender": "masculino",
    "age_range": "32-36 años",
    "voice_id": "voice-alvaro-1",
    "voice_name": "Zephyr (Voz aterciopelada y segura)",
    "avatar_url": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-fortunata",
    "book_id": "book-fortunata",
    "name": "Fortunata",
    "description": "Hermosa mujer de pueblo, de naturaleza pura y generosa, esclava de su amor por Juanito Santa Cruz.",
    "role": "protagonista",
    "personality": "Espontánea, bravía, leal y trágica",
    "gender": "femenino",
    "age_range": "21-25 años",
    "voice_id": "voice-fortunata-1",
    "voice_name": "Kore (Voz con fuerza castiza)",
    "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-jacinta",
    "book_id": "book-fortunata",
    "name": "Jacinta",
    "description": "Joven de la burguesía madrileña, bondadosa y prudente, atormentada por la infidelidad de su marido y su esterilidad.",
    "role": "protagonista",
    "personality": "Serena, compasiva, maternal y melancólica",
    "gender": "femenino",
    "age_range": "22-26 años",
    "voice_id": "voice-jacinta-1",
    "voice_name": "Puck (Voz refinada y suave)",
    "avatar_url": "https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-poeta",
    "book_id": "book-becquer",
    "name": "El Poeta / Narrador",
    "description": "Espíritu melancólico que recorre ruinas góticas y desentraña los misterios del amor inmaterial y la muerte.",
    "role": "narrador",
    "personality": "Enigmático, hipnótico, sombrío y poético",
    "gender": "masculino",
    "age_range": "28-33 años",
    "voice_id": "voice-becquer-1",
    "voice_name": "Fenrir (Voz profunda de susurro gótico)",
    "avatar_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "char-dama-verde",
    "book_id": "book-becquer",
    "name": "La Dama de los Ojos Verdes",
    "description": "Espíritu acuático de la fuente de los Álamos que atrae a los cazadores con su mirada esmeralda hacia las profundidades.",
    "role": "antagonista",
    "personality": "Seductora, espectral, fría y letal",
    "gender": "femenino",
    "age_range": "Intemporal",
    "voice_id": "voice-ojosverdes-1",
    "voice_name": "Kore (Eco sutil sobrenatural)",
    "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80"
  }
]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.adaptations
SELECT * FROM jsonb_populate_recordset(NULL::public.adaptations, '[
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-quijote-drama",
    "book_id": "book-quijote",
    "format": "drama",
    "status": "ready",
    "total_duration": 2160,
    "episode_count": 18,
    "description": "Serie en formato vertical 9:16 con diálogos tensos y cómicos entre Don Quijote y Sancho, con cliffhanger al final de cada episodio.",
    "aspect_ratio": "9:16"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-quijote-film",
    "book_id": "book-quijote",
    "format": "film",
    "status": "ready",
    "total_duration": 900,
    "episode_count": 1,
    "description": "Cortometraje cinematográfico en formato 16:9 que condensa la gran gesta y el despertar final de Alonso Quijano.",
    "aspect_ratio": "16:9"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-quijote-summary",
    "book_id": "book-quijote",
    "format": "summary",
    "status": "ready",
    "total_duration": 480,
    "episode_count": 1,
    "description": "Video-resumen narrativo dinámico con las ideas clave, metáforas centrales y argumento completo.",
    "aspect_ratio": "9:16"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-celestina-drama",
    "book_id": "book-celestina",
    "format": "drama",
    "status": "ready",
    "total_duration": 1800,
    "episode_count": 15,
    "description": "Microdrama en 9:16 centrado en la hechicería de Celestina, la desconfianza de los criados y el peligroso pacto de amor.",
    "aspect_ratio": "9:16"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-celestina-film",
    "book_id": "book-celestina",
    "format": "film",
    "status": "ready",
    "total_duration": 840,
    "episode_count": 1,
    "description": "Cortometraje gótico y pasional sobre la noche fatal en el huerto de Melibea.",
    "aspect_ratio": "16:9"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-celestina-summary",
    "book_id": "book-celestina",
    "format": "summary",
    "status": "ready",
    "total_duration": 420,
    "episode_count": 1,
    "description": "Resumen sintético de los 21 actos y el desenlace fatal de Fernando de Rojas.",
    "aspect_ratio": "9:16"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-regenta-drama",
    "book_id": "book-regenta",
    "format": "drama",
    "status": "ready",
    "total_duration": 2400,
    "episode_count": 20,
    "description": "Intriga psicológica y rumor social en Vetusta. Cada capítulo cierra en un punto de no retorno para Ana Ozores.",
    "aspect_ratio": "9:16"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-regenta-film",
    "book_id": "book-regenta",
    "format": "film",
    "status": "ready",
    "total_duration": 960,
    "episode_count": 1,
    "description": "Cortometraje de época que enfrenta la confesión en la catedral con el duelo en el parque.",
    "aspect_ratio": "16:9"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-regenta-summary",
    "book_id": "book-regenta",
    "format": "summary",
    "status": "ready",
    "total_duration": 510,
    "episode_count": 1,
    "description": "Claves del naturalismo español y el juicio moral a la sociedad provinciana decimonónica.",
    "aspect_ratio": "9:16"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-fortunata-drama",
    "book_id": "book-fortunata",
    "format": "drama",
    "status": "ready",
    "total_duration": 2040,
    "episode_count": 17,
    "description": "Pasión callejera y salones de alta sociedad en el Madrid de Galdós.",
    "aspect_ratio": "9:16"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-fortunata-film",
    "book_id": "book-fortunata",
    "format": "film",
    "status": "ready",
    "total_duration": 780,
    "episode_count": 1,
    "description": "Cortometraje dramático sobre el encuentro y el pacto de sangre de dos destinos cruzados.",
    "aspect_ratio": "16:9"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-fortunata-summary",
    "book_id": "book-fortunata",
    "format": "summary",
    "status": "ready",
    "total_duration": 450,
    "episode_count": 1,
    "description": "Video-resumen de la obra magna galdosiana.",
    "aspect_ratio": "9:16"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-becquer-drama",
    "book_id": "book-becquer",
    "format": "drama",
    "status": "ready",
    "total_duration": 1440,
    "episode_count": 12,
    "description": "Serie de relatos de terror romántico y apariciones medievales: El Monte de las Ánimas y Los Ojos Verdes.",
    "aspect_ratio": "9:16"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-becquer-film",
    "book_id": "book-becquer",
    "format": "film",
    "status": "ready",
    "total_duration": 720,
    "episode_count": 1,
    "description": "Corto de horror gótico centrado en la noche de difuntos en el Monte de las Ánimas.",
    "aspect_ratio": "16:9"
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "adapt-becquer-summary",
    "book_id": "book-becquer",
    "format": "summary",
    "status": "ready",
    "total_duration": 360,
    "episode_count": 1,
    "description": "Compendio poético y simbólico del mundo interior de Bécquer.",
    "aspect_ratio": "9:16"
  }
]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.episodes
SELECT * FROM jsonb_populate_recordset(NULL::public.episodes, '[
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-q-1",
    "adaptation_id": "adapt-quijote-drama",
    "book_id": "book-quijote",
    "number": 1,
    "title": "El delirio del hidalgo",
    "format": "drama",
    "thumbnail_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    "duration": 125,
    "is_free": true,
    "coin_price": 0,
    "story_position_start": 0,
    "story_position_end": 0.08,
    "cliffhanger": "Don Quijote empuña una vieja espada oxidada y jura que si Sancho no lo sigue, perderá el gobierno de la ínsula prometida.",
    "script_json": {
      "adaptation_id": "adapt-quijote-drama",
      "episode_number": 1,
      "cliffhanger_text": "¿Aceptará Sancho abandonar su hogar por la promesa de una ínsula imposible?",
      "scenes": [
        {
          "id": "scene-1-1",
          "setting": "Biblioteca polvorienta de Alonso Quijano, iluminada solo por velas que tiemblan con el viento nocturno.",
          "visual_prompt": "Cinematic close-up of an aged Spanish hidalgo with fierce, feverish eyes reading parchment under candlelight in an ancient library, 9:16 dramatic portrait.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
          "duration": 60,
          "lines": [
            {
              "id": "l-1",
              "character_id": "char-quijote",
              "character_name": "Don Quijote",
              "text": "¡El mundo duerme en la infamia mientras los agravios claman por acero y justicia!",
              "emotion": "apasionado",
              "duration_seconds": 6
            },
            {
              "id": "l-2",
              "character_id": "char-sancho",
              "character_name": "Sancho Panza",
              "text": "Señor Quijano, acuéstese que son las tres de la madrugada y las gallinas no han cantado todavía.",
              "emotion": "sarcástico",
              "duration_seconds": 7
            },
            {
              "id": "l-3",
              "character_id": "char-quijote",
              "character_name": "Don Quijote",
              "text": "¡No me llames Quijano, ignorante! Desde esta noche renazco como Don Quijote de la Mancha.",
              "emotion": "tenso",
              "duration_seconds": 7
            }
          ]
        },
        {
          "id": "scene-1-2",
          "setting": "Patio de armas improvisado frente al establo al alba.",
          "visual_prompt": "Early dawn misty countryside of La Mancha, silhouette of a tall lean knight mounting Rocinante, dramatic backlighting, 9:16 composition.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
          "duration": 65,
          "lines": [
            {
              "id": "l-4",
              "character_id": "char-sancho",
              "character_name": "Sancho Panza",
              "text": "¿Y qué gano yo, señor, dejando a mi mujer Teresa y a mis dos hijos por seguir su locura?",
              "emotion": "misterioso",
              "duration_seconds": 6
            },
            {
              "id": "l-5",
              "character_id": "char-quijote",
              "character_name": "Don Quijote",
              "text": "¡Una ínsula, Sancho! ¡Te haré gobernador de un reino entero antes de que caiga el solsticio!",
              "emotion": "furioso",
              "duration_seconds": 7
            }
          ]
        }
      ]
    }
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-q-2",
    "adaptation_id": "adapt-quijote-drama",
    "book_id": "book-quijote",
    "number": 2,
    "title": "Monstruos en el horizonte",
    "format": "drama",
    "thumbnail_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "duration": 118,
    "is_free": true,
    "coin_price": 0,
    "story_position_start": 0.08,
    "story_position_end": 0.16,
    "cliffhanger": "Don Quijote clava espuelas a Rocinante hacia las aspas giratorias sin escuchar los gritos desesperados de Sancho.",
    "script_json": {
      "adaptation_id": "adapt-quijote-drama",
      "episode_number": 2,
      "cliffhanger_text": "¿Sobrevivirá el caballero al impacto frontal de los supuestos gigantes de Briareo?",
      "scenes": [
        {
          "id": "scene-2-1",
          "setting": "Colina ventosa del Campo de Criptana con molinos de viento recortados contra el cielo carmesí.",
          "visual_prompt": "Windmills turning furiously on a dry plateau, dust storm, dramatic 9:16 angle looking up from horse level.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
          "duration": 118,
          "lines": [
            {
              "id": "l-6",
              "character_id": "char-quijote",
              "character_name": "Don Quijote",
              "text": "¡La ventura va guiando nuestras cosas mejor de lo que acertáramos a desear! ¿Ves allí, Sancho, treinta desaforados gigantes?",
              "emotion": "apasionado",
              "duration_seconds": 8
            },
            {
              "id": "l-7",
              "character_id": "char-sancho",
              "character_name": "Sancho Panza",
              "text": "¿Qué gigantes? ¡Mire bien vuestra merced que aquellos no son gigantes, sino molinos de viento, y lo que parecen brazos son las aspas!",
              "emotion": "tenso",
              "duration_seconds": 9
            },
            {
              "id": "l-8",
              "character_id": "char-quijote",
              "character_name": "Don Quijote",
              "text": "Bien se parece que no estás cursado en esto de las aventuras: ¡ellos son gigantes! Y si tienes miedo, ¡quítate de ahí y ponte en oración mientras yo entro con ellos en fiera y desigual batalla!",
              "emotion": "furioso",
              "duration_seconds": 12
            }
          ]
        }
      ]
    }
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-q-3",
    "adaptation_id": "adapt-quijote-drama",
    "book_id": "book-quijote",
    "number": 3,
    "title": "El bálsamo de Fierabrás",
    "format": "drama",
    "thumbnail_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "duration": 130,
    "is_free": true,
    "coin_price": 0,
    "story_position_start": 0.16,
    "story_position_end": 0.25,
    "cliffhanger": "El ventero exige el pago de la estancia y unos arrieros toman a Sancho por una manta al aire.",
    "script_json": {
      "adaptation_id": "adapt-quijote-drama",
      "episode_number": 3,
      "cliffhanger_text": "¿Podrá Don Quijote rescatar a Sancho antes de que lo manteen hasta la inconsciencia?",
      "scenes": [
        {
          "id": "scene-3-1",
          "setting": "Patio de una posada castellana que Don Quijote cree castillo encantado.",
          "visual_prompt": "Rustic Spanish inn courtyard at night, torches burning, shadows of laughing muleteers, 9:16 vertical cinematography.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
          "duration": 130,
          "lines": [
            {
              "id": "l-9",
              "character_id": "char-quijote",
              "character_name": "Don Quijote",
              "text": "¡Bebe, fiel escudero! Esta pócima cura las heridas del alma y los huesos quebrantados de todo caballero andante.",
              "emotion": "misterioso",
              "duration_seconds": 8
            },
            {
              "id": "l-10",
              "character_id": "char-sancho",
              "character_name": "Sancho Panza",
              "text": "¡Maldita sea la pócima, que las tripas se me revuelven como peces en sartén caliente!",
              "emotion": "melancólico",
              "duration_seconds": 8
            }
          ]
        }
      ]
    }
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-q-4",
    "adaptation_id": "adapt-quijote-drama",
    "book_id": "book-quijote",
    "number": 4,
    "title": "El yelmo de Mambrino",
    "format": "drama",
    "thumbnail_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    "duration": 115,
    "is_free": true,
    "coin_price": 0,
    "story_position_start": 0.25,
    "story_position_end": 0.35,
    "cliffhanger": "A lo lejos suena la trompeta de la Santa Hermandad: la guardia del rey los busca por bandoleros.",
    "script_json": {
      "adaptation_id": "adapt-quijote-drama",
      "episode_number": 4,
      "cliffhanger_text": "¿Será capturado el hidalgo antes de enviar su carta a Dulcinea?",
      "scenes": [
        {
          "id": "scene-4-1",
          "setting": "Camino real bajo una llovizna fina.",
          "visual_prompt": "Barber on donkey wearing a shiny brass basin on head, rainy road in medieval Spain, vertical frame 9:16.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
          "duration": 115,
          "lines": [
            {
              "id": "l-11",
              "character_id": "char-quijote",
              "character_name": "Don Quijote",
              "text": "¿Ves aquel que viene hacia nosotros sobre un caballo rucio rodado que trae en la cabeza un yelmo de oro?",
              "emotion": "apasionado",
              "duration_seconds": 8
            },
            {
              "id": "l-12",
              "character_id": "char-sancho",
              "character_name": "Sancho Panza",
              "text": "Lo que yo veo es un hombre sobre un asno pardo y una bacía de barbero reluciente para taparse del agua.",
              "emotion": "sarcástico",
              "duration_seconds": 8
            }
          ]
        }
      ]
    }
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-q-5",
    "adaptation_id": "adapt-quijote-drama",
    "book_id": "book-quijote",
    "number": 5,
    "title": "Liberación de los galeotes",
    "format": "drama",
    "thumbnail_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4",
    "duration": 140,
    "is_free": true,
    "coin_price": 0,
    "story_position_start": 0.35,
    "story_position_end": 0.45,
    "cliffhanger": "Los presos liberados le responden con una lluvia de piedras y Ginés de Pasamonte roba el asno de Sancho.",
    "script_json": {
      "adaptation_id": "adapt-quijote-drama",
      "episode_number": 5,
      "cliffhanger_text": "¿Cómo sobrevivirán en Sierra Morena sin montura ni comida?",
      "scenes": [
        {
          "id": "scene-5-1",
          "setting": "Desfiladero árido de Sierra Morena.",
          "visual_prompt": "Chained convicts guarded by musketeers on dusty ravine road, intense sun, high contrast 9:16.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
          "duration": 140,
          "lines": [
            {
              "id": "l-13",
              "character_id": "char-quijote",
              "character_name": "Don Quijote",
              "text": "Nadie puede forzar la voluntad de hombres libres. ¡Guardias, soltad las cadenas o probad mi lanza!",
              "emotion": "tenso",
              "duration_seconds": 7
            },
            {
              "id": "l-14",
              "character_id": "char-sancho",
              "character_name": "Sancho Panza",
              "text": "¡Señor, que van a galeras por ladrones y asesinos confesos! ¡No se meta con la justicia del rey!",
              "emotion": "furioso",
              "duration_seconds": 7
            }
          ]
        }
      ]
    }
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-q-6",
    "adaptation_id": "adapt-quijote-drama",
    "book_id": "book-quijote",
    "number": 6,
    "title": "Penitencia en Sierra Morena",
    "format": "drama",
    "thumbnail_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=600&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    "duration": 128,
    "is_free": false,
    "coin_price": 10,
    "story_position_start": 0.45,
    "story_position_end": 0.55,
    "cliffhanger": "El cura y el barbero del pueblo aparecen disfrazados en el bosque con una jaula de madera.",
    "script_json": {
      "adaptation_id": "adapt-quijote-drama",
      "episode_number": 6,
      "cliffhanger_text": "¿Es el fin de las andanzas o el inicio de una trampa mayor?",
      "scenes": [
        {
          "id": "scene-6-1",
          "setting": "Cumbre rocosa de Sierra Morena.",
          "visual_prompt": "Knight stripping off armor on mountain peak, dramatic storm clouds, vertical 9:16.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
          "duration": 128,
          "lines": [
            {
              "id": "l-15",
              "character_id": "char-quijote",
              "character_name": "Don Quijote",
              "text": "Haré aquí la penitencia más desgarradora que caballero alguno haya hecho por su señora: rasgaré mis vestiduras y me daré de cabezadas contra las rocas.",
              "emotion": "melancólico",
              "duration_seconds": 10
            }
          ]
        }
      ]
    }
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-q-7",
    "adaptation_id": "adapt-quijote-drama",
    "book_id": "book-quijote",
    "number": 7,
    "title": "El caballero de la Blanca Luna",
    "format": "drama",
    "thumbnail_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    "duration": 155,
    "is_free": false,
    "coin_price": 15,
    "story_position_start": 0.85,
    "story_position_end": 0.95,
    "cliffhanger": "La lanza del caballero rival derriba a Don Quijote en la playa de Barcelona. La espada apunta a su garganta.",
    "script_json": {
      "adaptation_id": "adapt-quijote-drama",
      "episode_number": 7,
      "cliffhanger_text": "¿Confesará Don Quijote que su dama no es la más bella para salvar la vida?",
      "scenes": [
        {
          "id": "scene-7-1",
          "setting": "Playa de Barcelona con el mar encrespado al atardecer.",
          "visual_prompt": "Two armored knights facing each other on wet sand, breaking waves, dusk cinematic 9:16.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
          "duration": 155,
          "lines": [
            {
              "id": "l-16",
              "character_id": "char-quijote",
              "character_name": "Don Quijote",
              "text": "Dulcinea del Toboso es la más hermosa mujer del mundo, y yo el más desdichado caballero de la tierra, y no es bien que mi flaqueza desmienta esta verdad. ¡Aprieta, caballero, la lanza, y quítame la vida, pues me has quitado la honra!",
              "emotion": "apasionado",
              "duration_seconds": 14
            }
          ]
        }
      ]
    }
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-q-film-1",
    "adaptation_id": "adapt-quijote-film",
    "book_id": "book-quijote",
    "number": 1,
    "title": "El ocaso del caballero andante",
    "format": "film",
    "thumbnail_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "duration": 900,
    "is_free": false,
    "coin_price": 25,
    "story_position_start": 0,
    "story_position_end": 1,
    "cliffhanger": "El retorno final a la cordura y el adiós de Sancho ante el lecho de muerte de Alonso Quijano el Bueno.",
    "script_json": {
      "adaptation_id": "adapt-quijote-film",
      "episode_number": 1,
      "scenes": [
        {
          "id": "scene-film-1",
          "setting": "Llanuras infinitas de La Mancha, paso del tiempo con luz dorada crepuscular.",
          "visual_prompt": "Panoramic wide landscape 16:9 of two silhouettes on horse and donkey traversing golden wheatfields.",
          "visual_mode": "premium",
          "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=80",
          "duration": 900,
          "lines": [
            {
              "id": "fl-1",
              "character_id": "char-quijote",
              "character_name": "Don Quijote",
              "text": "Sábete, Sancho, que no es un hombre más que otro si no hace más que otro.",
              "emotion": "melancólico",
              "duration_seconds": 8
            },
            {
              "id": "fl-2",
              "character_id": "char-sancho",
              "character_name": "Sancho Panza",
              "text": "No se muera vuestra merced, señor mío, sino tome mi consejo y viva muchos años; porque la mayor locura que puede hacer un hombre en esta vida es dejarse morir sin más ni más.",
              "emotion": "apasionado",
              "duration_seconds": 11
            }
          ]
        }
      ]
    }
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-q-sum-1",
    "adaptation_id": "adapt-quijote-summary",
    "book_id": "book-quijote",
    "number": 1,
    "title": "Don Quijote en 8 minutos: Mito y Tragedia",
    "format": "summary",
    "thumbnail_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "duration": 480,
    "is_free": true,
    "coin_price": 0,
    "story_position_start": 0,
    "story_position_end": 1,
    "cliffhanger": "Por qué Don Quijote no es una sátira cómica, sino el nacimiento de la novela moderna.",
    "script_json": {
      "adaptation_id": "adapt-quijote-summary",
      "episode_number": 1,
      "scenes": [
        {
          "id": "scene-sum-1",
          "setting": "Espacio conceptual con ilustraciones renacentistas animadas y mapas de la época.",
          "visual_prompt": "High fidelity book summary infographics, parchment textures, animated classical typography, 9:16 format.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
          "duration": 480,
          "lines": [
            {
              "id": "sl-1",
              "character_id": "char-quijote",
              "character_name": "Narrador Lámina",
              "text": "Publicado en dos partes (1605 y 1615), Don Quijote desmonta las novelas de caballerías para inventar la novela polifónica moderna. A través del choque entre el idealismo quijotesco y el realismo sanchopancesco, Cervantes demuestra que la realidad depende de los ojos que la contemplan.",
              "emotion": "neutro",
              "duration_seconds": 18
            }
          ]
        }
      ]
    }
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-c-1",
    "adaptation_id": "adapt-celestina-drama",
    "book_id": "book-celestina",
    "number": 1,
    "title": "El dardo del amor en el huerto",
    "format": "drama",
    "thumbnail_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    "duration": 120,
    "is_free": true,
    "coin_price": 0,
    "story_position_start": 0,
    "story_position_end": 0.12,
    "cliffhanger": "Sempronio toca a la puerta clandestina de Celestina mientras la tormenta arrecia sobre la ciudad.",
    "script_json": {
      "adaptation_id": "adapt-celestina-drama",
      "episode_number": 1,
      "cliffhanger_text": "¿Aceptará Celestina el encargo de doblegar el orgullo de Melibea?",
      "scenes": [
        {
          "id": "scene-c1-1",
          "setting": "Jardín renacentista cercado por altos muros con cipreses.",
          "visual_prompt": "Secret moonlit garden in medieval Salamanca, beautiful proud noblewoman turning away from young kneeling aristocrat, 9:16 portrait.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
          "duration": 120,
          "lines": [
            {
              "id": "cl-1",
              "character_id": "char-calisto",
              "character_name": "Calisto",
              "text": "¡En esto veo, Melibea, la grandeza de Dios!",
              "emotion": "apasionado",
              "duration_seconds": 5
            },
            {
              "id": "cl-2",
              "character_id": "char-melibea",
              "character_name": "Melibea",
              "text": "¿En qué, Calisto?",
              "emotion": "tenso",
              "duration_seconds": 3
            },
            {
              "id": "cl-3",
              "character_id": "char-calisto",
              "character_name": "Calisto",
              "text": "En dar poder a natura que de tan perfecta hermosura te dotase... ¡Melibeo soy y a Melibea adoro!",
              "emotion": "apasionado",
              "duration_seconds": 8
            },
            {
              "id": "cl-4",
              "character_id": "char-melibea",
              "character_name": "Melibea",
              "text": "¡Vete de aquí, torpe loco, antes de que ordene a mis criados que laven esta afrenta con tu sangre!",
              "emotion": "furioso",
              "duration_seconds": 7
            }
          ]
        }
      ]
    }
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-c-2",
    "adaptation_id": "adapt-celestina-drama",
    "book_id": "book-celestina",
    "number": 2,
    "title": "El cordón de la doncella",
    "format": "drama",
    "thumbnail_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "duration": 135,
    "is_free": true,
    "coin_price": 0,
    "story_position_start": 0.12,
    "story_position_end": 0.28,
    "cliffhanger": "Celestina sale de la mansión apretando el cordón bendito de Melibea mientras ríe con crueldad.",
    "script_json": {
      "adaptation_id": "adapt-celestina-drama",
      "episode_number": 2,
      "cliffhanger_text": "¿Es el cordón una prenda de amor o el instrumento de la condenación?",
      "scenes": [
        {
          "id": "scene-c2-1",
          "setting": "Salón señorial de la casa de Pleberio.",
          "visual_prompt": "Dark medieval interior, old crone whispering into the ear of a young weeping noblewoman, dramatic chiaroscuro 9:16.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80",
          "duration": 135,
          "lines": [
            {
              "id": "cl-5",
              "character_id": "char-celestina",
              "character_name": "Celestina",
              "text": "Un dolor de muelas padece aquel triste caballero que con solo una palabra tuya o el roce de tu cordón consagrado sanaría.",
              "emotion": "misterioso",
              "duration_seconds": 9
            },
            {
              "id": "cl-6",
              "character_id": "char-melibea",
              "character_name": "Melibea",
              "text": "¡Quebrántase mi pecho! Tómalo, vieja, pero no le digas de dónde viene...",
              "emotion": "melancólico",
              "duration_seconds": 7
            }
          ]
        }
      ]
    }
  },
  {
    "created_at": "2026-01-01T00:00:00Z",
    "id": "ep-r-1",
    "adaptation_id": "adapt-regenta-drama",
    "book_id": "book-regenta",
    "number": 1,
    "title": "El catalejo sobre Vetusta",
    "format": "drama",
    "thumbnail_url": "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=600&q=80",
    "video_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "duration": 130,
    "is_free": true,
    "coin_price": 0,
    "story_position_start": 0,
    "story_position_end": 0.1,
    "cliffhanger": "Don Fermín espía a Ana Ozores saliendo a su jardín y aprieta el puño contra la piedra de la torre.",
    "script_json": {
      "adaptation_id": "adapt-regenta-drama",
      "episode_number": 1,
      "cliffhanger_text": "¿Confesará el Magistral su obsesión antes de que Álvaro Mesía se acerque a ella?",
      "scenes": [
        {
          "id": "scene-r1-1",
          "setting": "Torre de la catedral de Oviedo / Vetusta en una tarde gris y húmeda.",
          "visual_prompt": "Gothic cathedral bell tower overlooking a misty 19th century Spanish northern city, priest looking through spyglass, 9:16 portrait.",
          "visual_mode": "economic",
          "image_url": "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80",
          "duration": 130,
          "lines": [
            {
              "id": "rl-1",
              "character_id": "char-fermin",
              "character_name": "Don Fermín de Pas",
              "text": "Toda Vetusta a mis pies como un nido de hormigas... Y en medio de este lodo, ella: Ana, la única alma digna de ser conquistada.",
              "emotion": "tenso",
              "duration_seconds": 10
            }
          ]
        }
      ]
    }
  }
]'::jsonb)
ON CONFLICT (id) DO NOTHING;
