import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Plus, Save, Users, Clapperboard, Image as ImageIcon, Upload, Loader2 } from 'lucide-react';
import { supabaseClient, getAccessToken } from '../../lib/supabaseClient';

const api=async(path:string, options:RequestInit={})=>{
 const token=await getAccessToken();
 const res=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});
 const data=await res.json().catch(()=>({}));
 if(!res.ok) throw new Error(data.error||'Error de servidor');
 return data;
};

export const CreatorEpisodeScreen:React.FC=()=>{
 const {projectId,episodeId}=useParams();
 const [episode,setEpisode]=useState<any>(null),[script,setScript]=useState(''),[sceneTitle,setSceneTitle]=useState(''),[sceneScript,setSceneScript]=useState(''),[characterName,setCharacterName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [scenes,setScenes]=useState<any[]>([]),[characters,setCharacters]=useState<any[]>([]),[media,setMedia]=useState<any[]>([]),[uploading,setUploading]=useState(false);
 const load=async()=>{try{const [e,c,ch,m]=await Promise.all([api(`/api/creator/episodes/${episodeId}`),api(`/api/creator/episodes/${episodeId}/scenes`),api(`/api/creator/projects/${projectId}/characters`),api(`/api/creator/projects/${projectId}/media`)]);setEpisode(e.episode);setScript(e.episode.script?.text||'');setScenes(c.scenes||[]);setCharacters(ch.characters||[]);setMedia(m.media||[])}catch(e){setError(e instanceof Error?e.message:'Error')}};
 useEffect(()=>{load()},[episodeId,projectId]);
 const save=async()=>{setBusy(true);try{await api(`/api/creator/episodes/${episodeId}`,{method:'PATCH',body:JSON.stringify({script:{text:script}})});setBusy(false)}catch(e){setError(e instanceof Error?e.message:'Error');setBusy(false)}};
 const addScene=async(e:React.FormEvent)=>{e.preventDefault();if(!sceneTitle)return;setBusy(true);try{await api(`/api/creator/episodes/${episodeId}/scenes`,{method:'POST',body:JSON.stringify({title:sceneTitle,script:sceneScript})});setSceneTitle('');setSceneScript('');await load()}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}};
 const uploadFile=async(file:File)=>{if(!projectId)return;setUploading(true);setError('');try{const kind=file.type.startsWith('image/')?'image':file.type.startsWith('audio/')?'audio':file.type.startsWith('video/')?'video':'other';const prep=await api(`/api/creator/projects/${projectId}/media/upload-url`,{method:'POST',body:JSON.stringify({name:file.name,mime_type:file.type,kind})});if(!supabaseClient)throw new Error('Configura Supabase en el cliente para subir archivos.');const uploaded=await supabaseClient.storage.from('media').uploadToSignedUrl(prep.path,prep.token,file);if(uploaded.error)throw uploaded.error;await api(`/api/creator/projects/${projectId}/media`,{method:'POST',body:JSON.stringify({name:file.name,mime_type:file.type,kind,storage_key:prep.path,episode_id:episodeId,size_bytes:file.size})});await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo subir el archivo')}finally{setUploading(false)}};
 const addCharacter=async(e:React.FormEvent)=>{e.preventDefault();if(!characterName)return;setBusy(true);try{await api(`/api/creator/projects/${projectId}/characters`,{method:'POST',body:JSON.stringify({name:characterName})});setCharacterName('');await load()}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}};
 return <div className="min-h-screen bg-[#090a0f] text-slate-100 pb-24"><div className="max-w-6xl mx-auto px-4 py-8 space-y-6">
  <Link to={`/studio/project/${projectId}`} className="inline-flex items-center gap-2 text-xs text-slate-400"><ArrowLeft className="w-4 h-4"/>Proyecto</Link>
  {error&&<div className="p-3 rounded-2xl bg-rose-500/10 border border-rose-500/30 text-rose-300">{error}</div>}
  {episode&&<><div><p className="text-amber-400 text-xs font-bold uppercase">Episodio</p><h1 className="text-3xl font-black">{episode.title}</h1></div>
  <section className="grid lg:grid-cols-2 gap-5">
   <div className="p-5 rounded-3xl bg-slate-900 border border-slate-800 space-y-3"><div className="flex items-center justify-between"><h2 className="font-bold flex gap-2 items-center"><Save className="w-4 h-4"/>Guion</h2><button onClick={save} disabled={busy} className="px-3 py-2 rounded-xl bg-amber-500 text-slate-950 font-bold text-sm">Guardar</button></div><textarea value={script} onChange={e=>setScript(e.target.value)} rows={14} placeholder="Escribe el guion del episodio..." className="w-full p-4 rounded-2xl bg-slate-950 border border-slate-800 outline-none"/></div>
   <div className="p-5 rounded-3xl bg-slate-900 border border-slate-800 space-y-4"><h2 className="font-bold flex gap-2 items-center"><Clapperboard className="w-4 h-4"/>Escenas</h2><form onSubmit={addScene} className="space-y-2"><input value={sceneTitle} onChange={e=>setSceneTitle(e.target.value)} placeholder="Título de escena" className="w-full p-3 rounded-xl bg-slate-950 border border-slate-800"/><textarea value={sceneScript} onChange={e=>setSceneScript(e.target.value)} placeholder="Texto / acción de la escena" rows={4} className="w-full p-3 rounded-xl bg-slate-950 border border-slate-800"/><button disabled={busy} className="px-4 py-2 rounded-xl bg-slate-100 text-slate-950 font-bold flex gap-2 items-center"><Plus className="w-4 h-4"/>Añadir escena</button></form><div className="space-y-2">{scenes.map((s,i)=><div key={s.id} className="p-3 rounded-xl bg-slate-950"><b>{i+1}. {s.title}</b><p className="text-xs text-slate-400 mt-1">{s.script?.text||''}</p></div>)}</div></div>
  </section>
  <section className="p-5 rounded-3xl bg-slate-900 border border-slate-800 space-y-4"><h2 className="font-bold flex gap-2 items-center"><Users className="w-4 h-4"/>Personajes</h2><form onSubmit={addCharacter} className="flex gap-2"><input value={characterName} onChange={e=>setCharacterName(e.target.value)} placeholder="Nombre del personaje" className="flex-1 p-3 rounded-xl bg-slate-950 border border-slate-800"/><button disabled={busy} className="px-4 py-2 rounded-xl bg-amber-500 text-slate-950 font-bold"><Plus className="w-4 h-4"/></button></form><div className="grid sm:grid-cols-3 gap-3">{characters.map(c=><div key={c.id} className="p-4 rounded-xl bg-slate-950"><b>{c.name}</b><p className="text-xs text-slate-400 mt-1">{c.description||'Sin descripción'}</p></div>)}</div></section>
  <section className="p-5 rounded-3xl bg-slate-900 border border-slate-800 space-y-4"><div className="flex items-center justify-between"><h2 className="font-bold flex gap-2 items-center"><ImageIcon className="w-4 h-4"/>Biblioteca multimedia</h2><label className="cursor-pointer px-4 py-2 rounded-xl bg-amber-500 text-slate-950 font-bold text-sm flex gap-2 items-center">{uploading?<Loader2 className="w-4 h-4 animate-spin"/>:<Upload className="w-4 h-4"/>}{uploading?'Subiendo...':'Subir archivo'}<input type="file" className="hidden" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)uploadFile(f);e.currentTarget.value=''}}/></label></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{media.map(m=><div key={m.id} className="p-4 rounded-xl bg-slate-950 border border-slate-800"><p className="font-semibold truncate">{m.name}</p><p className="text-xs text-slate-500 mt-1">{m.kind} · {m.status}</p><a className="text-xs text-amber-400 mt-2 inline-block" href={`/api/media?key=${encodeURIComponent(m.storage_key)}`} target="_blank" rel="noreferrer">Abrir</a></div>)}</div></section>
  </>}
 </div></div>;
};