import { SEED_ADAPTATIONS, SEED_BOOKS, SEED_CHARACTERS, SEED_EPISODES } from '../src/data/seedBooks';

// Inserts rows via jsonb_populate_recordset so every column comes straight from
// the TypeScript seed objects; keys that are not table columns are ignored.
function insertRows(table: string, rows: object[]): string {
  const json = JSON.stringify(rows, null, 2).replace(/'/g, "''");
  return [
    `INSERT INTO public.${table}`,
    `SELECT * FROM jsonb_populate_recordset(NULL::public.${table}, '${json}'::jsonb)`,
    'ON CONFLICT (id) DO NOTHING;',
  ].join('\n');
}

export function buildSeedSql(): string {
  const withTimestamps = <T extends object>(rows: T[]) =>
    rows.map(row => ({ created_at: '2026-01-01T00:00:00Z', ...row }));

  return [
    '-- AUTO-GENERATED by scripts/generate-seed.ts from src/data/seedBooks.ts. Do not edit by hand.',
    '-- Regenerate with: bun run db:seed',
    '',
    insertRows('books', withTimestamps(SEED_BOOKS)),
    '',
    insertRows('characters', withTimestamps(Object.values(SEED_CHARACTERS).flat())),
    '',
    insertRows('adaptations', withTimestamps(Object.values(SEED_ADAPTATIONS).flat())),
    '',
    insertRows('episodes', withTimestamps(Object.values(SEED_EPISODES).flat())),
    '',
  ].join('\n');
}
